services:
  email-service:
    build: .
    image: email-service:latest
    container_name: email-service
    env_file:
      - path: .env
        required: false
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
